version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: labfaz_pg
    restart: always
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    volumes:
      - labfaz_pg:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  labfaz_pg:
